name: 🐛 Баг-репорт
description: Если что-то работает не так.
labels: ["status:triage", "type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        - Баг-репорты нужны для сообщения о неправильно работающих вещах.
        - Попробуй [поискать в существующих репортах](https://github.com/danganronpa-online/public-gmod/issues), может быть, кто-то уже рассказал об этом
        - Каждая ошибка должна быть в отдельном репорте, не стоит создавать списки
  - type: textarea
    id: what-happened
    attributes:
      label: Что наблюдается?
      description: Опиши подробно, что именно происходит на момент написания репорта
      placeholder: Кнопка не нажимается, ничего не происходит...
    validations:
      required: true
  - type: textarea
    id: correct-behaviour
    attributes:
      label: Как это должно работать?
      description: Как, по твоему мнению, это должно работать, что нужно изменить
      placeholder: После нажатия кнопки должно открываться меню!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Как это повторить?
      description: Пошагово опиши, как повторить эту ошибку
      placeholder: 1) Открыть меню на клавишу X. 2) Нажать на кнопку ABC. 3) ???
    validations:
      required: false
  - type: textarea
    id: console-errors
    attributes:
      label: Ошибки в консоли
      description: Если при этом в консоли появлялись какие-то ошибки, скопируй их сюда
      placeholder: |
       [investigation] addons/dro/class_trial.lua:208: bad argument #1 to 'maxn' (table expected, got nil)
        1. maxn - [C]:-1
          2. func - addons/investigation/lua/modules/evidence/cl_evidence.lua:208
            3. unknown - lua/includes/extensions/net.lua:32
      render: shell
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Обратная связь
      description: Если нам понадобится что-то уточнить, как с тобой связаться?
      placeholder: "например, Discord: username#1234 или VK: https://vk.com/mikvoin"
    validations:
      required: false
